### ISSUE TITLE
kube-cnc-router cannot be created while using long hostnames

### ISSUE THREAD

**Issue by patsch9** [citrix/citrix-k8s-node-controller#32]
We have autogenerated hostnames in our cluster with a length of 52 chars. 
The cnc-controller now try to create the cnc-router pod by using kube-cnc-router- + Hostname as Container name selected by the kubernetes.io/hostname label (`/go/src/citrix-node-controller/vendor/kube.router/create.go:397`).

The length of containernames in Kubernetes must be maximum 63 chars so the container cant be created by following error
` Failed to Create a Pod Pod "kube-cnc-router-xxx-xxxxxxxxxx-xxxxxxx-xxxxxx-xxxxxx-ffc84de5-gkp6x" is invalid: spec.containers[0].name: Invalid value: "kube-cnc-router-xxx-xxxxxxxxxx-xxxxxxx-xxxxxx-xxxxxx-ffc84de5-gkp6x": must be no more than 63 characters`

Please add a possibility to define another label or something for generating the container name.

**Comment by apoorva-05** [comment]
@patsch9 This issue is now addressed in the latest release of [2.2.10](https://github.com/citrix/citrix-k8s-node-controller/releases/tag/v2.2.10).
Containers are now always deployed with the fixed name `kube-cnc-router`. 
kube-cnc-router pod name prefixes can now be customized with `CNC_ROUTER_NAME` environment variable. Since pod name limit is 253 characters it should be able to accommodate a large hostname(max length 63).
For more details: [Release Notes]( https://github.com/citrix/citrix-k8s-node-controller/releases/tag/v2.2.10 )
